# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
SYNCBIN=$HOME/syncbin

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# ZSH_THEME="jemus42"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# ~/.oh-my-zsh/plugins/* –– Custom plugins ~/.oh-my-zsh/custom/plugins/
# plugins=(rsync extract zsh-syntax-highlighting git-flow-completion zsh-autosuggestions z)
# source $ZSH/oh-my-zsh.sh

source $SYNCBIN/zsh/aliases;
source $SYNCBIN/zsh/functions;
source $SYNCBIN/zsh/envars;

test -e "${HOME}/.path.local" && source "${HOME}/.path.local"
test -e "${HOME}/.functions.local" && source "${HOME}/.functions.local"

test -e "${HOME}/.travis/travis.sh" && source "${HOME}/.travis/travis.sh"
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


###############
### Antigen ###
###############
function source_if_possible() {
    if [[ -r $1 ]]; then source $1; fi
}

case $( uname -s ) in
Linux)  
    case $( hostname ) in
        kitchensink) source $HOME/.antigen.zsh;;
        pfannkuchen) source $HOME/.antigen.zsh;;
        *) source $(brew --prefix)/share/antigen/antigen.zsh;;
    esac;;
Darwin) 
    source $(brew --prefix)/share/antigen/antigen.zsh;;
FreeBSD) 
    source /usr/local/share/zsh-antigen/antigen.zsh;;
*) 
    source $HOME/.antigen.zsh;;
esac


# Only execute if antigen commend is present, i.e. skip on FreeBSD
$(command -v antigen) init $SYNCBIN/zsh/antigen

### Prompt ###

## In case of pure prompt:
# autoload -U promptinit; promptinit
# prompt pure