# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="jemus42"

# Example aliases
alias zshconfig="nano ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github rsync osx ruby extract zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin
# Setting locale to ensure UTF8
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# Make system ruby work
export GEM_HOME=~/.gem
export PATH=$PATH:~/.gem/bin

if [[ $(whoami) == "Lukas" ]]; then 

	SYNCBIN="/Users/Lukas/repos/jemus42/syncbin";

		elif [[ $(hostname) == "wurstmineberg.de" ]]; then

			SYNCBIN="/home/jemus42/syncbin";

		elif [[ $(hostname) == "wurstmannberg.de" ]]; then

			SYNCBIN="/home/jemus/syncbin";

fi

source $SYNCBIN/zsh/aliases;
source $SYNCBIN/functions;

if [[ -f ~/.path.local ]]; then source ~/.path.local; else touch ~/.path.local; fi
