# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
SYNCBIN=$HOME/syncbin

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="jemus42"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# ~/.oh-my-zsh/plugins/* –– Custom plugins ~/.oh-my-zsh/custom/plugins/
# plugins=(rsync extract zsh-syntax-highlighting git-flow-completion zsh-autosuggestions z)

# source $ZSH/oh-my-zsh.sh

source $SYNCBIN/zsh/aliases;
source $SYNCBIN/functions;
source $SYNCBIN/zsh/envars;

test -e "${HOME}/.path.local" && source ~/.path.local
test -e "${HOME}/.functions.local" && source ~/.functions.local

# added by travis gem
[ -f /Users/Lukas/.travis/travis.sh ] && source /Users/Lukas/.travis/travis.sh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


###############
### Antigen ###
###############
case $( uname -s ) in
Linux)  source /home/linuxbrew/.linuxbrew/share/antigen/antigen.zsh;;
Darwin) source /usr/local/share/antigen/antigen.zsh
;;
esac

$(command -v antigen) init $SYNCBIN/zsh/antigen

### Prompt ###

## In case of pure prompt:
# autoload -U promptinit; promptinit
# prompt pure

# Liquidprompt, only load in interactive shell
[[ $- = *i* ]] && source $HOME/syncbin/zsh/liquidpromptrc